/** @type {import('tailwindcss').Config} */
/*eslint-env node*/
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    colors: {
      white: "#FFFFFE",
      black: "#231F20",
      primary: "#8917F2",
      error: "#DB0DB6",
      dark_grey: "#221f201a",
      purple_1: "#FAF5FF",
      purple_2: "#F7EFFF",
      purple_3: "#EBDDF9",
      purple_4: "#D8BFF0",
      purple_5: "#B07AF0",
      purple_6: "#9C41FF",
      purple_7: "#8917F2",
      purple_8: "#4E0D8A",
      pink_1: "#FEEFFC",
      pink_2: "#FACDF2",
      pink_3: "#F078DB",
      pink_4: "#DB0DB6",
      neon_6: "#C6FF00",
      neon_7: "#EBFFA4",
      green_1: "#FCFFD8",
      green_2: "#FCFFC7",
      green_3: "#F6FAA0",
      green_4: "#E6ED5D",
      green_5: "#D6DE23",
      green_6: "#C6CE05",
      green_7: "#ADB500",
      green_8: "#7E8400",
      green_9: "#ACF6CC",
      blue_1: "#F0F2FF",
      blue_2: "#DFE2FF",
      blue_3: "#BDC3FC",
      blue_5: "#6D6DFA",
      blue_7: "#2D19F7",
      blue_8: "#4C3BFA",
      grey: "#00000029",
      grey_1: "#F7F7F7",
      grey_2: "#F2F2F2",
      grey_3: "#DCDDDE",
      grey_4: "#B5B3B7",
      grey_5: "#878689",
      grey_6: "#D9D9D9",
      grey_7: "#515151",
    },
    extend: {
      width: {
        85: "330px",
        82.5: "327.5px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
